apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"ingress-web-base","namespace":"vikram"},"spec":{"ingressClassName":"traefik","rules":[{"host":"web.tooskaoil.com","http":{"paths":[{"backend":{"service":{"name":"factory-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}},{"host":"www.web.tooskaoil.com","http":{"paths":[{"backend":{"service":{"name":"factory-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}},{"host":"nexus.tooskaoil.com","http":{"paths":[{"backend":{"service":{"name":"vikram-cluster","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["web.tooskaoil.com","nexus.tooskaoil.com","skooner.tooskaoil.com","www.nexus.tooskaoil.com","www.web.tooskaoil.com"],"secretName":"nexus-tls"}]}}
  creationTimestamp: "2025-05-07T07:17:27Z"
  generation: 5
  name: ingress-web-base
  namespace: vikram
  resourceVersion: "26095153"
  uid: d1039d43-16cd-468e-a76b-9338aab5fda9
spec:
  ingressClassName: traefik
  rules:
  - host: web.tooskaoil.com
    http:
      paths:
      - backend:
          service:
            name: factory-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: www.web.tooskaoil.com
    http:
      paths:
      - backend:
          service:
            name: factory-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: nexus.tooskaoil.com
    http:
      paths:
      - backend:
          service:
            name: vikram-cluster
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - web.tooskaoil.com
    - nexus.tooskaoil.com
    - skooner.tooskaoil.com
    - www.nexus.tooskaoil.com
    - www.web.tooskaoil.com
    secretName: nexus-new
status:
  loadBalancer:
    ingress:
    - ip: 172.19.22.243
